OUTPUT_PATH: "Output/"
SCHOLAR_DATA: "Scholars_data.csv"
TOP_K_SCHOLARS: 20
CPU_COUNT: 20
PUBLICATION_DATASET: "PublicationDataset.csv"
ANALYTICAL_DATASET: "AnalyticalDatabase.csv"
SCHOLARS_DATASET: "ScholarsDataset.csv"
RECOMMENDED_DATASET: 'Recommendations.csv'
UNIV_DETAILS : {'TAMU':{'BASE_URL': "https://api.library.tamu.edu/scholars-discovery/individual/search/advanced?page=1&size=", 
                  'END_URL': "&sort=name_sort,asc&fl=name&class.filter=Person&class.opKey=EQUALS&filters=class",'PROFILE_URL': "https://api.library.tamu.edu/scholars-discovery/individual/",'STOPWORDS' : ["texas","university","qatar", "may","business","school","transportation","institute"]}}
PRETRAINED_MODELS: ['stsb-roberta-large', 'all-MiniLM-L6-v2', 'all-mpnet-base-v2']
